### ISSUE TITLE
Create GET request to get a single client data

### ISSUE THREAD

**Issue by devendra-dantal04** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#10]
Create a controller to get client data from the database using the client ID.

Make changes in the `controllers/main.controllers.js` file

Project and Client Data are provided in the `data` folder

Refer `models` folder for the database schema

**Comment by ujwalkumar1995** [comment]
@devendra-dantal04 @VighneshManjrekar  I would like to work on this. Could you please assign?
Also do you only want name, email and phone of the client in the response or also the id along with it?

**Comment by VighneshManjrekar** [comment]
@ujwalkumar1995 Need complete response along with client ref

**Comment by Aritra056GITHUB** [comment]
Please assign me this task

**Comment by ujwalkumar1995** [comment]
Hey @VighneshManjrekar 
Could you please review the PR and let me know if anything needs to be changed.

**Comment by VighneshManjrekar** [comment]
@ujwalkumar1995 I already reviewed PR #13 and requested some changes do the changes so I can merge it

**Comment by ujwalkumar1995** [comment]
Hey @VighneshManjrekar 
Sorry but I am not able to find your requested changes. Could you please point me where you have mentioned them?

**Comment by VighneshManjrekar** [comment]
@ujwalkumar1995 work on the pull request today itself

**Comment by ujwalkumar1995** [comment]
Hey @VighneshManjrekar
Have submitted the changes. Please review.
