### ISSUE TITLE
Create GET request to get a single project data 

### ISSUE THREAD

**Issue by devendra-dantal04** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#11]
Create a controller to get project data from the database using the project ID.

Make changes in the `controllers/main.controllers.js` file

Project and Client Data are provided in the `data` folder

Refer `models` folder for the database schema

**Comment by Gowrishankar04** [comment]
Hi @devendra-dantal04 ,

Can you please assign this to me?

Thanks

**Comment by VighneshManjrekar** [comment]
No response from @Gowrishankar04 since 5 days so removing him as assignee

**Comment by Gowrishankar04** [comment]
Hi @VighneshManjrekar,

After getting assigned to myself, I started the work. But last four days, I was occupied some other work. Again I started yesterday, can you please reassign this to me?

Thanks

**Comment by VighneshManjrekar** [comment]
@Gowrishankar04 sure

**Comment by Gowrishankar04** [comment]
@VighneshManjrekar - Apologies for the delay

**Comment by Gowrishankar04** [comment]
Hi @devendra-dantal04 / @VighneshManjrekar ,

I have raised PR: https://github.com/Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022/pull/21.
Please review and merge it.

Thanks

**Comment by VighneshManjrekar** [comment]
@Gowrishankar04 Thanks for your contribution :)
