### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by VighneshManjrekar** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#23]
* Convert how to contribute section of README.md to more detailed CONTRIBUTING.md file
* Link CONTRIBUTING.md to the README.md file in how to contribute section with text "know more"
* Include information about open source and hacktoberfest

**Comment by MansiBhayade** [comment]
can you assign this issue to me..?

**Comment by PavvanPradeep** [comment]
can i work on this issue

**Comment by VighneshManjrekar** [comment]
@PavvanPradeep issue is already assigned to @MansiBhayade

**Comment by HydraPhyzer** [comment]
> @PavvanPradeep issue is already assigned to @MansiBhayade

Hey Sir, I have Good Experience in Readme.md Customization. Could You Please Assign This to me? It Would be Ultra Fast. I Would  Appreciate that if you could assign it to me

Thanks, and Waiting for your Reply

**Comment by VighneshManjrekar** [comment]
@HydraPhyzer issue is resolved by @MansiBhayade if you have new changes or modification create issue and mention your propose changes there
