### ISSUE TITLE
Create a PUT request to update project.

### ISSUE THREAD

**Issue by Yash-Desai-1** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#4]
Edit code from `controllers/main.controllers.js` 
Use you own data or seed database using `node seeder.js -i` command

**Comment by rohanny** [comment]
Assign me this issue

**Comment by VighneshManjrekar** [comment]
@rohannY work on the pull request today itself

**Comment by VighneshManjrekar** [comment]
#20
