### ISSUE TITLE
Create POST request to create new client

### ISSUE THREAD

**Issue by devendra-dantal04** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#5]
Create a controller to create a new client in the database.

Make changes in the `controllers/main.controllers.js` file

Project and Client Data are provided in the `data` folder

Refer `models` folder for database schema

**Comment by Hrx4** [comment]
assign me the issue , i will do it.

**Comment by VighneshManjrekar** [comment]
Work on this issue only

**Comment by Hrx4** [comment]
Hey @VighneshManjrekar  i am unable to run it. Can you help me
![WhatsApp Image 2022-10-16 at 8 42 34 PM](https://user-images.githubusercontent.com/90823608/196043328-5e89fa7b-7738-4dc5-ad87-da6b87767d71.jpeg)

**Comment by VighneshManjrekar** [comment]
You already using 7000 port you have 2 options
1. Kill previous instance
2. Change PORT variable in `configs/.env`

**Comment by PrathameshPawar119** [comment]
May I solve this issue @VighneshManjrekar sir ?

**Comment by VighneshManjrekar** [comment]
@PrathameshPawar119 sure sir!

**Comment by VighneshManjrekar** [comment]
#25
