### ISSUE TITLE
Create a DELETE request to delete a project

### ISSUE THREAD

**Issue by rashmod** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#6]
Create a controller to Delete a project using the given id

Make changes in the file `controllers/main.controllers.js`

**Comment by Hrx4** [comment]
i would like to take this issue.

**Comment by VighneshManjrekar** [comment]
@Hrx4 I appreciate your response but I can assign one issue to one contributor only I already assigned #5 issue to you kindly work on that issue

**Comment by biohazard2117** [comment]
I would like to work on this issue. Can you assign it to me ? @VighneshManjrekar

**Comment by VighneshManjrekar** [comment]
@biohazard2117 Sure

**Comment by VighneshManjrekar** [comment]
#19
