### ISSUE TITLE
Create DELETE request to delete a client

### ISSUE THREAD

**Issue by devendra-dantal04** [Google-Developer-Students-Club-DMCE/project-mgmt-api-hacktober2022#8]
Create a controller to delete client data from the database using the client ID.

Make changes in the `controllers/main.controllers.js` file

Project and Client Data are provided in the `data` folder

Refer `models` folder for the database schema

**Comment by biohazard2117** [comment]
@VighneshManjrekar I can work on these all issues. Assign them to me

**Comment by VighneshManjrekar** [comment]
Work only on this issue. Leave other issues for other contributors.

**Comment by VighneshManjrekar** [comment]
#12
